[build]  
  command = "npm install && npm run build"  
  functions = "netlify-functions"  
  publish = "Counties and Unitary Authorities in England Deploy/views"  
  runtime = "nodejs20.x"
[functions]  
  node_bundler = "esbuild"
[[redirects]]  
  force = true  
  from = "/api/*"  
  status = 200  
  to = "/.netlify/functions/api/:splat"
