[build]
  command = "npm install && npm run build"
  functions = "netlify-functions"
  publish = "views"
  runtime = "nodejs20.x"
  timeout = 20 


[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
