[build]
  command = "npm install && npm run build && node node_modules/pug-cli/api.js views/ --out ./"
  functions = "netlify-functions"
  publish = "views"
  runtime = "nodejs20.x"
  timeout = 20

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"